"""Constants for the Needle Conversation integration."""

DOMAIN = "needle"

CONF_CONFIDENCE_THRESHOLD = "confidence_threshold"
CONF_MAX_CALLS = "max_calls"
CONF_TIMEOUT = "timeout"

DEFAULT_CONFIDENCE_THRESHOLD = 0.80
DEFAULT_MAX_CALLS = 4
DEFAULT_TIMEOUT = 120

MIN_CONFIDENCE_THRESHOLD = 0.0
MAX_CONFIDENCE_THRESHOLD = 1.0
MIN_MAX_CALLS = 1
MAX_MAX_CALLS = 8
MIN_TIMEOUT = 10
MAX_TIMEOUT = 300

